### ISSUE TITLE
Cannot use in Electron

### ISSUE THREAD

**Issue by aabluedragon** [leenjewel/node-kcp#9]
When trying to require the npm lib in an Electron app, you get the following error
```
Uncaught (in promise) Error: Loading non-context-aware native module in renderer: '\\?\C:\Users\alona\dev\MyProj\app\node_modules\node-kcp-token\build\Release\kcp.node'. See https://github.com/electron/electron/issues/18397.
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\alona\dev\MyProj\app\node_modules\node-kcp-token\index.js:1:173)
```

It appears that the following fork fixed it, however fails to compile on win 32 bit, upon `npm install`
https://github.com/bruce48x/node-kcp

**Comment by leenjewel** [comment]
Try to edit node-kcp.cc line 29

From

```
    NODE_MODULE(kcp, InitModule)
```

Change to

```
NAN_MODULE_WORKER_ENABLED(kcp, InitModule)
```

And then rebuild?

**Comment by aabluedragon** [comment]
Now the error is different:
```
Error: Module did not self-register: '\\?\C:\Users\alona\dev\NukemNet\app\node_modules\node-kcp\build\Release\kcp.node'.
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\alona\dev\NukemNet\app\electron_preload.js:3:13)
(anonymous) @ node:electron/js2c/renderer_init:2
```

**Comment by aabluedragon** [comment]
If I `require()` in plain NodeJS (without Electron) it's working fine:
```javascript
const kcp = require('node-kcp/build/Release/kcp.node');
```

**Comment by aabluedragon** [comment]
After some changes, I got it to work by modifying one of the forks.
With the following fork, it works on Electron and 32-bit windows:
https://github.com/aabluedragon/node-kcp
